version: '3.8'

services:
  flinvent-111:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flinvent-111
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - infra

networks:
  infra:
    external: true
